device_tracker.38a4ed16f6f8:
  friendly_name: fina_phone
device_tracker.iphonedistopherhome:
  hidden: true
device_tracker.galaxya52017home:
  hidden: true
device_tracker.7c49eb12b925:
  friendly_name: living_light_sofa
  hidden: true
device_tracker.08eca9c5efbe:
  hidden: true
device_tracker.30aea40de594:
  hidden: true
device_tracker.34f39a5ea62d:
  hidden: true
device_tracker.58fb847b53ef:
  hidden: true
device_tracker.80d21d333f79:
  hidden: true
device_tracker.windows4k3njb3home:
  hidden: true
device_tracker.d0d2b06069df:
  hidden: true
device_tracker.bcddc2fe338f:
  friendly_name: hydroponic_ctrl
  hidden: true
light.living_room:
  hidden: true
light.group_for_wakeup:
  hidden: true
