
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
http_password: pass
latitude: 0
longitude: 0
city: city
country_code: US
province_code: CA

base_url: url.com
airvisual_api_key: a
waki_token: a
telegram_api_key: 1
telegram_chat_id: 1
google_assistant_project_id: a
google_assistant_api_key: a
xiami_miio_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
